version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/static
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGO_URI=mongodb://mongo:27017/chatbot
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    container_name: chatbot_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
